# Index

[[redirects]]
  from = "/index.html"
  to = "/"

# Features

[[redirects]]
  from = "/corriganville.html"
  to = "/features/corriganville"

[[redirects]]
  from = "/corriganville.html"
  to = "/features/corriganville"

[[redirects]]
  from = "/corriganville_tour.html"
  to = "/features/corriganville-park"

[[redirects]]
  from = "/douglas-fairbanks-triangle-fine-arts.html"
  to = "/features/douglas-fairbanks-at-triangle-fine-arts"

[[redirects]]
  from = "/great-american-films-1911-1920.html"
  to = "/features/great-american-films-part-1"

[[redirects]]
  from = "/great-american-films-1921-1929.html"
  to = "/features/great-american-films-part-2"

[[redirects]]
  from = "/john-ford-harry-carey.html"
  to = "/features/john-ford-and-harry-carey-at-universal-studios"

[[redirects]]
  from = "/extant-american-silent-films-1919-1931.html"
  to = "/features/american-silent-treasures"

[[redirects]]
  from = "/lost-american-silent-films-1919-1931.html"
  to = "/features/lost-american-silent-treasures"

[[redirects]]
  from = "/outstanding-speaking-voices-english-men.html"
  to = "/features/outstanding-speaking-voices"

[[redirects]]
  from = "/outstanding-speaking-voices-english-men.html"
  to = "/features/outstanding-speaking-voices"

[[redirects]]
  from = "/donovan-affair-reconstructing-soundtrack.html"
  to = "/features/reconstructing-the-donovan-affairs-sound"

[[redirects]]
  from = "/tcm-film-festival-2012.html"
  to = "/features/tcm-2012"

[[redirects]]
  from = "/tcm-film-festival-2013.html"
  to = "/features/tcm-2013"

[[redirects]]
  from = "/tcm-film-festival-2014.html"
  to = "/features/tcm-2014"

[[redirects]]
  from = "/tcm-film-festival-2015.html"
  to = "/features/tcm-2015"

[[redirects]]
  from = "/tcm-film-festival-2016.html"
  to = "/features/tcm-2016"

[[redirects]]
  from = "/ten-great-horror-film-locations.html"
  to = "/features/ten-great-horror-film-locations"

[[redirects]]
  from = "/strangler-of-the-swamp-fahrmann-maria.html"
  to = "/features/the-two-marias"

[[redirects]]
  from = "/underrated-science-fiction-films-1950s.html"
  to = "/features/underrated-sci-fi-films-of-the-1950s"

[[redirects]]
  from = "/william-fox-biography-book-review.html"
  to = "/features/william-fox-and-the-fox-film-corporation"

# People

[[redirects]]
  from = "/dorothy-arzner.html"
  to = "/people/dorothy-arzner"

[[redirects]]
  from = "/lionel-barrymore.html"
  to = "/people/lionel-barrymore"

[[redirects]]
  from = "/madge-bellamy.html"
  to = "/people/madge-bellamy"

[[redirects]]
  from = "/eleanor-boardman.html"
  to = "/people/eleanor-boardman"

[[redirects]]
  from = "/johnny-mack-brown.html"
  to = "/people/johnny-mack-brown"

[[redirects]]
  from = "/harry-carey.html"
  to = "/people/harry-carey"

[[redirects]]
  from = "/jewel-carmen.html"
  to = "/people/jewel-carmen"

[[redirects]]
  from = "/ray-crash-corrigan.html"
  to = "/people/ray-crash-corrigan"

[[redirects]]
  from = "/ricardo-cortez.html"
  to = "/people/ricardo-cortez"

[[redirects]]
  from = "/marion-davies.html"
  to = "/people/marion-davies"

[[redirects]]
  from = "/marie-dressler.html"
  to = "/people/marie-dressler"

[[redirects]]
  from = "/deanna-durbin.html"
  to = "/people/deanna-durbin"

[[redirects]]
  from = "/john-emerson.html"
  to = "/people/john-emerson"

[[redirects]]
  from = "/kay-francis.html"
  to = "/people/kay-francis"

[[redirects]]
  from = "/hoot-gibson.html"
  to = "/people/hoot-gibson"

[[redirects]]
  from = "/john-gilbert.html"
  to = "/people/john-gilbert"

[[redirects]]
  from = "/dorothy-gish.html"
  to = "/people/dorothy-gish"

[[redirects]]
  from = "/lawrence-gray.html"
  to = "/people/lawrence-gray"

[[redirects]]
  from = "/alice-guy-blache.html"
  to = "/people/alice-guy-blache"

[[redirects]]
  from = "/raymond-hackett.html"
  to = "/people/raymond-hackett"

[[redirects]]
  from = "/william-haines.html"
  to = "/people/william-haines"

[[redirects]]
  from = "/dell-henderson.html"
  to = "/people/dell-henderson"

[[redirects]]
  from = "/max-linder.html"
  to = "/people/max-linder"

[[redirects]]
  from = "/edmund-lowe.html"
  to = "/people/edmund-lowe"

[[redirects]]
  from = "/frances-marion.html"
  to = "/people/frances-marion"

[[redirects]]
  from = "/claire-mcdowell.html"
  to = "/people/claire-mcdowell"

[[redirects]]
  from = "/coleen-moore.html"
  to = "/people/coleen-moore"

[[redirects]]
  from = "/elliot-nugent.html"
  to = "/people/elliot-nugent"

[[redirects]]
  from = "/franklin-pangborn.html"
  to = "/people/franklin-pangborn"

[[redirects]]
  from = "/charles-ray.html"
  to = "/people/charles-ray"

[[redirects]]
  from = "/wallace-reid.html"
  to = "/people/wallace-reid"

[[redirects]]
  from = "/alma-rubens.html"
  to = "/people/alma-rubens"

[[redirects]]
  from = "/donald-ogden-stewart.html"
  to = "/people/donald-ogden-stewart"

[[redirects]]
  from = "/lee-tracy.html"
  to = "/people/lee-tracy"

[[redirects]]
  from = "/king-vidor.html"
  to = "/people/king-vidor"

