# Index

[[redirects]]
  from = "/index.html"
  to = "/"

# Features

[[redirects]]
  from = "/corriganville.html"
  to = "/features/corriganville"

[[redirects]]
  from = "/corriganville.html"
  to = "/features/corriganville"

[[redirects]]
  from = "/corriganville_tour.html"
  to = "/features/corriganville-park"

[[redirects]]
  from = "/douglas-fairbanks-triangle-fine-arts.html"
  to = "/features/douglas-fairbanks-at-triangle-fine-arts"

[[redirects]]
  from = "/great-american-films-1911-1920.html"
  to = "/features/great-american-films-part-1"

[[redirects]]
  from = "/great-american-films-1921-1929.html"
  to = "/features/great-american-films-part-2"

[[redirects]]
  from = "/john-ford-harry-carey.html"
  to = "/features/john-ford-and-harry-carey-at-universal-studios"

[[redirects]]
  from = "/extant-american-silent-films-1919-1931.html"
  to = "/features/american-silent-treasures"

[[redirects]]
  from = "/lost-american-silent-films-1919-1931.html"
  to = "/features/lost-american-silent-treasures"

[[redirects]]
  from = "/outstanding-speaking-voices-english-men.html"
  to = "/features/outstanding-speaking-voices"

[[redirects]]
  from = "/outstanding-speaking-voices-english-men.html"
  to = "/features/outstanding-speaking-voices"

[[redirects]]
  from = "/donovan-affair-reconstructing-soundtrack.html"
  to = "/features/reconstructing-the-donovan-affairs-sound"

[[redirects]]
  from = "/tcm-film-festival-2012.html"
  to = "/features/tcm-2012"

[[redirects]]
  from = "/tcm-film-festival-2013.html"
  to = "/features/tcm-2013"

[[redirects]]
  from = "/tcm-film-festival-2014.html"
  to = "/features/tcm-2014"

[[redirects]]
  from = "/tcm-film-festival-2015.html"
  to = "/features/tcm-2015"

[[redirects]]
  from = "/tcm-film-festival-2016.html"
  to = "/features/tcm-2016"

[[redirects]]
  from = "/ten-great-horror-film-locations.html"
  to = "/features/ten-great-horror-film-locations"

[[redirects]]
  from = "/strangler-of-the-swamp-fahrmann-maria.html"
  to = "/features/the-two-marias"

[[redirects]]
  from = "/underrated-science-fiction-films-1950s.html"
  to = "/features/underrated-sci-fi-films-of-the-1950s"

[[redirects]]
  from = "/william-fox-biography-book-review.html"
  to = "/features/william-fox-and-the-fox-film-corporation"

# People

[[redirects]]
  from = "/dorothy-arzner.html"
  to = "/people/dorothy-arzner"