/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudiosIndexRouteImport } from './routes/studios.index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as FilmsIndexRouteImport } from './routes/films.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as PeopleSlugRouteImport } from './routes/people/$slug'
import { Route as FilmsSlugRouteImport } from './routes/films/$slug'
import { Route as FeaturesSlugRouteImport } from './routes/features/$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosIndexRoute = StudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/search': typeof SearchRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/studios/': typeof StudiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/search': typeof SearchRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/features': typeof FeaturesIndexRoute
  '/films': typeof FilmsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/studios': typeof StudiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/search': typeof SearchRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/studios/': typeof StudiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/search'
    | '/features/$slug'
    | '/films/$slug'
    | '/people/$slug'
    | '/features/'
    | '/films/'
    | '/people/'
    | '/studios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/search'
    | '/features/$slug'
    | '/films/$slug'
    | '/people/$slug'
    | '/features'
    | '/films'
    | '/people'
    | '/studios'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/search'
    | '/features/$slug'
    | '/films/$slug'
    | '/people/$slug'
    | '/features/'
    | '/films/'
    | '/people/'
    | '/studios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  SearchRoute: typeof SearchRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  StudiosIndexRoute: typeof StudiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/': {
      id: '/studios/'
      path: '/studios'
      fullPath: '/studios/'
      preLoaderRoute: typeof StudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  SearchRoute: SearchRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  FilmsIndexRoute: FilmsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  StudiosIndexRoute: StudiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
